- name: Install 
  hosts: all
  tasks:
  - name: Install IIS (Web-Server only)
    win_feature:
      name: Web-Server
      state: present

  - name: Install IIS (Web-Server and Web-Common-Http)
    win_feature:
      name:
      - Web-Server
      - Web-Common-Http
      - Management-Tools
      state: present
      
 
