- name: Install 
  hosts: all
  tasks:
  - name: Install IIS (Web-Server and Web-Common-Http)
    win_feature:
      name:
      - Web-Server
      - Web-Common-Http
      state: present
      
  - name: Install IIS Web-Server with sub features and management tools
    win_feature:
     name: Web-Http-Redirect,Web-Dyn-Compression,Web-Basic-Auth,Web-Net-Ext45,Web-Asp,Web-Asp-Net45,Web-ISAPI-Ext,Web-ISAPI-Filter,Web-WebSockets,Web-Mgmt-Console,Web-Mgmt-Service
     state: present
