- name: Install 
  hosts: all
  tasks:
  - name: Install IIS (Web-Server only)
    win_feature:
      name: Web-Server
      state: present

  - name: Install IIS (Web-Server and Web-Common-Http)
    win_feature:
      name:
      - Web-Server
      - Web-Common-Http
      state: present
      
  - name: Install IIS Web-Server with sub features and management tools
    win_feature:
     name: Web-Server
     state: present
     include_sub_features: yes
     include_management_tools: yes
    register: win_feature     
  
 
